const tragos = [
  {
    nombre: "Mojito",
    tipo: "con-alcohol",
    imagen: "mojito.jpg",
    descripcion: "Refrescante trago cubano con ron, lima, menta y soda.",
    ingredientes: ["50ml ron blanco", "1 lima", "10 hojas de menta", "Soda", "Azúcar"],
    pasos:["Machacar la lima con azúcar y menta.","Agregar ron y hielo.","Completar con soda y revolver."],
  },
  {
    nombre: "Limonada",
    tipo: "sin-alcohol",
    imagen: "limonada.jpg",
    descripcion: "Bebida refrescante a base de jugo de limón.",
    ingredientes: ["3 limones", "500ml agua", "Azúcar a gusto", "Hielo"],
    pasos:["Mezclar jugo de limón con azúcar.","Agregar vodka y agua/soda.","Servir con hielo."],
  },
  {
    nombre: "Daikiri",
    tipo: "con-alcohol",
    imagen: "daikiri.jpg",
    descripcion: "Cóctel elegante y seco.",
    ingredientes: ["50 ml de ron blanco", "Jugo de 1 lima", "1 cda de azúcar", "Hielo"],
    pasos:["Colocar todos los ingredientes en la licuadora.","Triturar hasta obtener una mezcla homogénea.","Servir frío en copa."],
  },
   {
    nombre: "Martini",
    tipo: "con-alcohol",
    imagen: "martini.jpg",
    descripcion: "Cóctel elegante y seco.",
    ingredientes: ["60 ml de ginebra","10 ml de vermut seco","1 aceituna o twist de limón","Hielo"],
    pasos:["Revolver ginebra y vermut con hielo.","Colar en copa fría.","Decorar con aceituna o limón."]
  },
   {
    nombre: "Piña Colada",
    tipo: "con-alcohol",
    imagen: "pcolada.jpg",
    descripcion: "Tropical, dulce y cremoso.",
    ingredientes: ["60 ml de ron blanco", "30 ml de crema de coco", "30 ml de jugo de piña", "Hielo"],
    pasos:["Licuar ron, piña y crema de coco con hielo.","Servir en vaso alto.","Decorar con piña o cereza."],
  }, 
  {
    nombre: "Negroni",
    tipo: "con-alcohol",
    imagen: "negroni.jpg",
    descripcion: "Clásico italiano, amargo y aromático.",
    ingredientes: ["30 ml de ginebra", "30 ml de Campari", "30 ml de vermut rojo dulce", "Rodaja de naranja", "Hielo"],
    pasos: ["Mezclar todo en vaso con hielo.","Revolver suavemente.","Decorar con naranja."],
  },
   {
    nombre: "Perla Negra",
    tipo: "con-alcohol",
    imagen: "pnegra.jpg",
    descripcion: "Shot fuerte y energético, muy popular en boliches.",
    ingredientes: ["30 ml de Jägermeister","1 lata de bebida energizante (tipo Red Bull).","Hielo."],
    pasos:["Colocar el shot de Jägermeister dentro del vaso (queda “invertido”).","Completar con la bebida energizante por encima."],
  },
   {
    nombre: "Cosmopolitan",
    tipo: "con-alcohol",
    imagen: "cosmopolitan.jpg",
    descripcion: "Cóctel moderno, cítrico y frutal.",
    ingredientes: ["40 ml de vodka", "20 ml de triple sec", "20 ml de jugo de arándano", "20 ml de jugo de lima", "Hielo"],
    pasos:["Agitar todos los ingredientes con hielo.","Colar en copa de cóctel.","Decorar con twist de naranja."],
  },
  {
    nombre: "Sangría",
    tipo: "con-alcohol",
    imagen: "sangria.jpg",
    descripcion: "Bebida festiva con vino y frutas.",
    ingredientes: ["1 botella de vino tinto.","1 naranja."," 1 manzana."," 1 limón.","2 cdas de azúcar.","Soda o jugo de naranja.", "Azúcar a gusto.", "Hielo."],
    pasos:["Cortar las frutas en trozos.","Mezclar con vino y azúcar.","Reposar y servir con hielo y soda."],
  },
{
    nombre: "Campari",
    tipo: "con-alcohol",
    imagen: "campari.jpg",
    descripcion: "Refrescante y amargo.",
    ingredientes: ["50 ml de Campari","100 ml de jugo de naranja", "Hielo"],
    pasos:["Llenar vaso con hielo.","Añadir Campari y jugo.","Revolver y servir."],
},
{
    nombre: "Malibú",
    tipo: "con-alcohol",
    imagen: "malibu.jpg",
    descripcion: "Cóctel tropical, dulce y exótico con ron de coco.",
    ingredientes: ["40 ml de Malibú (ron de coco)","20 ml de ron blanco","60 ml de jugo de mango","Hielo"],
    pasos:["Llenar vaso con hielo.","Añadir Malibú, ron blanco y jugo de mango.","Revolver y servir."],
},
{
    nombre: "Caipirinha",
    tipo: "con-alcohol",
    imagen: "caipirinha.jpg",
    descripcion: "Cóctel brasileño fresco y ácido.",
    ingredientes: ["50 ml de cachaça","1 lima","2 cdas de azúcar","Hielo"],
    pasos:["Machacar la lima con azúcar.","Agregar cachaça y hielo.","Revolver y servir."],
},
{
    nombre: "Margarita",
    tipo: "con-alcohol",
    imagen: "margarita.jpg",
    descripcion: "Equilibrio perfecto entre ácido y dulce.",
    ingredientes: ["40 ml de tequila","20 ml de triple sec","20 ml de jugo de lima","Sal","Hielo"],
    pasos:["Escarchar la copa con sal.","Agitar tequila, triple sec y lima con hielo.","Colar y servir."],
},
];